# Generated by Django 5.2.17 on 2026-09-11 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['CARETAKER', 'ESTATE_MANAGER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('structural', 'Structural'), ('appliance', 'Appliance'), ('pest', 'Pest Control'), ('security', 'Security'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='properties.estate'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='properties.room'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['status', 'priority'], name='maintenance_status_76175b_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['tenant', 'status'], name='maintenance_tenant__ff4dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['estate', 'status'], name='maintenance_estate__0454a2_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['assigned_to', 'status'], name='maintenance_assigne_c047d3_idx'),
        ),
    ]
