# Generated by Django 5.2.17 on 2026-09-11 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caretaker', models.ForeignKey(blank=True, limit_choices_to={'role': 'CARETAKER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caretaker_estates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_estates', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(blank=True, limit_choices_to={'role': 'LANDLORD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_estates', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'ESTATE_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_estates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('assign_manager_estate', 'Can assign a manager to an estate'), ('assign_caretaker_estate', 'Can assign a caretaker to an estate'), ('generate_units_estate', 'Can generate units for an estate')],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='properties.estate')),
                ('main_tenant', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['TENANT', 'SUB_TENANT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_houses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['house_number'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('is_occupied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.house')),
                ('main_tenant', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['TENANT', 'SUB_TENANT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['room_name'],
            },
        ),
        migrations.AddIndex(
            model_name='estate',
            index=models.Index(fields=['location', 'name'], name='properties__locatio_91239d_idx'),
        ),
        migrations.AddIndex(
            model_name='estate',
            index=models.Index(fields=['landlord'], name='properties__landlor_1d7384_idx'),
        ),
        migrations.AddIndex(
            model_name='estate',
            index=models.Index(fields=['manager'], name='properties__manager_71001d_idx'),
        ),
        migrations.AddIndex(
            model_name='estate',
            index=models.Index(fields=['caretaker'], name='properties__caretak_aac916_idx'),
        ),
        migrations.AddConstraint(
            model_name='estate',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='uniq_estate_name_per_location'),
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['estate', 'house_number'], name='properties__estate__35fc85_idx'),
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['main_tenant'], name='properties__main_te_7ad469_idx'),
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.UniqueConstraint(fields=('estate', 'house_number'), name='uniq_house_number_per_estate'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['house', 'is_occupied'], name='properties__house_i_116768_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['main_tenant'], name='properties__main_te_2cd634_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('house', 'room_name'), name='uniq_room_name_per_house'),
        ),
    ]
