# Generated by Django 5.2.17 on 2026-09-11 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MPESATransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=15)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='leasing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_mp_status_69aafe_idx'), models.Index(fields=['tenant', 'status'], name='payments_mp_tenant__2fe360_idx'), models.Index(fields=['invoice', 'status'], name='payments_mp_invoice_d54e40_idx'), models.Index(fields=['phone_number'], name='payments_mp_phone_n_3895b2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='mpesa_amount_non_negative')],
            },
        ),
    ]
