# Generated by Django 5.2.17 on 2026-09-11 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lease_holder', models.BooleanField(default=True, help_text='True if this tenant is the primary lease holder for the room.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rent_due_day', models.PositiveSmallIntegerField()),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('next_invoice_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leases', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.room')),
                ('tenant', models.ForeignKey(limit_choices_to={'role__in': ['TENANT', 'SUB_TENANT']}, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField(db_index=True)),
                ('base_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utility_bills_split', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_fee_charged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('pdf_file', models.URLField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='leasing.leaseagreement')),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['status', 'next_invoice_date'], name='leasing_lea_status_bf64c6_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['tenant', 'status'], name='leasing_lea_tenant__a0afd0_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['room', 'status'], name='leasing_lea_room_id_66a170_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaseagreement',
            constraint=models.CheckConstraint(condition=models.Q(('rent_due_day__gte', 1), ('rent_due_day__lte', 28)), name='lease_rent_due_day_valid'),
        ),
        migrations.AddConstraint(
            model_name='leaseagreement',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent__gte', 0)), name='lease_rent_non_negative'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='leasing_inv_status_a6a017_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['lease', 'status'], name='leasing_inv_lease_i_29e544_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='leasing_inv_due_dat_e42bff_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('lease', 'period_start'), name='uniq_invoice_per_lease_period'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('balance_due__gte', 0)), name='invoice_balance_non_negative'),
        ),
    ]
