# Generated by Django 5.2.17 on 2026-09-11 21:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('LANDLORD', 'Landlord'), ('ESTATE_MANAGER', 'Estate Manager'), ('CARETAKER', 'Caretaker'), ('AGENT', 'Agent'), ('ACCOUNTANT', 'Accountant'), ('TENANT', 'Tenant'), ('SUB_TENANT', 'Sub-Tenant')], db_index=True, default='SUB_TENANT', max_length=32)),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=15)),
                ('national_id', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('id_type', models.CharField(blank=True, choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('DRIVER_LICENSE', "Driver's License"), ('ALIEN_ID', 'Alien ID')], default='NATIONAL_ID', max_length=20)),
                ('kra_pin', models.CharField(blank=True, default='', max_length=11)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=15)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
                'indexes': [models.Index(fields=['role', 'is_active'], name='users_user_role_e1ec1a_idx'), models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'), models.Index(fields=['national_id'], name='users_user_nationa_7d24c6_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
